"""initial tables

Revision ID: 26b431c647c3
Revises: 
Create Date: 2026-09-21 01:16:20.638968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b431c647c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', name='userstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('change_log',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity', sa.Enum('memory', 'tag', 'memory_tag', 'setting', name='changeentity', native_enum=False, length=16), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('upsert', 'delete', name='changeaction', native_enum=False, length=16), nullable=False),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_change_log_user_id_users')),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_change_log'))
    )
    op.create_index('ix_change_log_user_seq', 'change_log', ['user_id', 'seq'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('audio', 'text', name='memorytype', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('audio_object_key', sa.Text(), nullable=True),
    sa.Column('audio_duration_ms', sa.Integer(), nullable=True),
    sa.Column('audio_format', sa.String(length=16), nullable=True),
    sa.Column('audio_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.Enum('record', 'quick_note', name='memorysource', native_enum=False, length=16), nullable=False),
    sa.Column('record_status', sa.Enum('normal', 'incomplete', name='recordstatus', native_enum=False, length=16), nullable=False),
    sa.Column('client_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    op.create_index('ix_memories_user_created_at', 'memories', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_memories_user_server_version', 'memories', ['user_id', 'server_version'], unique=False)
    op.create_table('settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_settings_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'key', name=op.f('pk_settings'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tags_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index('uq_tags_user_name_active', 'tags', ['user_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.create_table('memory_tags',
    sa.Column('memory_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], name=op.f('fk_memory_tags_memory_id_memories')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_memory_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('memory_id', 'tag_id', name=op.f('pk_memory_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_tags')
    op.drop_index('uq_tags_user_name_active', table_name='tags', postgresql_where=sa.text('deleted_at IS NULL'), sqlite_where=sa.text('deleted_at IS NULL'))
    op.drop_table('tags')
    op.drop_table('settings')
    op.drop_index('ix_memories_user_server_version', table_name='memories')
    op.drop_index('ix_memories_user_created_at', table_name='memories')
    op.drop_table('memories')
    op.drop_index('ix_change_log_user_seq', table_name='change_log')
    op.drop_table('change_log')
    op.drop_table('users')
    # ### end Alembic commands ###
